In [1]:
## reload submodule
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

import qfin

In [ ]:
data = pd.read_csv("./data/_^spx.csv", index_col=0, parse_dates=[0], sep=",")
data

In [4]:
backtest_params = {
    "initial_balance": 10000,
    "default_entry_value": 1,
    "default_entry_value_max": 1000000,
    "commission": 0.001,
}

bt = qfin.Backtester(dataset=data, **backtest_params)

for broker in bt.run():
    current_bar = broker.state.data.iloc[-1]
    previous_bar = broker.state.data.iloc[-2]

    current_signal = current_bar["signal"]
    previous_signal = previous_bar["signal"]
    changed = current_signal != previous_signal

    if changed:
        if current_signal == 1:
            broker.buy()
        elif current_signal == -1:
            broker.sell()
        else:
            broker.close()

In [5]:
trades = bt.trades()
trades.columns

Index(['is_long', 'leverage', 'entry_value', 'entry_price', 'entry_bar',
       'entry_commission', 'entry_time', 'exit_value', 'exit_price',
       'exit_commission', 'exit_bar', 'exit_time', 'pnl', 'return_pct'],
      dtype='object')

In [6]:
trades[["is_long", "entry_time", "entry_price", "exit_price", "pnl", "return_pct"]]

    is_long entry_time  entry_price   exit_price          pnl  return_pct
0     False 2023-02-02  4179.759766  3861.590088   823.110431    0.082393
1      True 2023-03-10  3861.590088  4588.959961  2034.570360    0.188360
2     False 2023-07-31  4588.959961  4117.370117  1468.497034    0.114537
3      True 2023-10-27  4117.370117  5254.350098  3941.641614    0.276142
4     False 2024-03-28  5254.350098  4967.229980  1051.633991    0.057803
5      True 2024-04-19  4967.229980  5667.200195  2709.115261    0.140918
6     False 2024-07-16  5667.200195  5186.330078  2031.404040    0.092719
7      True 2024-08-05  5186.330078  5648.399902  2130.656820    0.089094
8     False 2024-08-30  5648.399902  5408.419922  1154.426476    0.044372
9      True 2024-09-06  5408.419922  6090.270020  3422.020296    0.126072
10    False 2024-12-06  6090.270020  5827.040039  1379.223826    0.045174
11     True 2025-01-10  5827.040039  5937.339844   603.406215    0.018929
12    False 2025-01-16  5937.339844  6086.370117  -794.512970   -0.024486
13     True 2025-01-22  6086.370117  6118.709961   168.025324    0.005313
14    False 2025-01-23  6118.709961  6012.279785   562.193536    0.017702
15     True 2025-01-27  6012.279785  6144.149902   708.184584    0.021933
16    False 2025-02-19  6144.149902  5521.520020  3716.976373    0.112764
17     True 2025-03-13  5521.520020  5776.649902  1692.958152    0.046206
18    False 2025-03-25  5776.649902  5062.250000  5403.877607    0.141123

In [7]:
history = bt.history()
history.columns

Index(['close', 'balance', 'equity', 'commission', 'long', 'short', 'signal',
       'buy_hold'],
      dtype='object')

In [8]:
history.tail(20)

,close,balance,equity,commission,long,short,signal,buy_hold
date,,,,,,,,
2025-03-11,5572.069824,32995,36346,806,False,True,-1,14570.779262
2025-03-12,5599.299805,32995,36169,806,False,True,-1,14641.984765
2025-03-13,5521.520020,32995,36679,806,True,False,1,14438.593186
2025-03-14,5638.939941,36675,37418,879,True,False,1,14745.642418
2025-03-17,5675.120117,36675,37658,879,True,False,1,14840.252388
2025-03-18,5614.660156,36675,37257,879,True,False,1,14682.151579
2025-03-19,5675.290039,36675,37659,879,True,False,1,14840.696728
2025-03-20,5662.890137,36675,37577,879,True,False,1,14808.271391
2025-03-21,5667.560059,36675,37608,879,True,False,1,14820.483083
2025-03-24,5767.569824,36675,38271,879,True,False,1,15082.005330
2025-03-25,5776.649902,36675,38331,879,False,True,-1,15105.749435
2025-03-26,5712.200195,38330,38724,956,False,True,-1,14937.215572
2025-03-27,5693.310059,38330,38852,956,False,True,-1,14887.818486
2025-03-28,5580.939941,38330,39634,956,False,True,-1,14593.974327
2025-03-31,5611.850098,38330,39416,956,False,True,-1,14674.803368
2025-04-01,5633.069824,38330,39267,956,False,True,-1,14730.292255
2025-04-02,5670.970215,38330,39005,956,False,True,-1,14829.400530
2025-04-03,5396.520020,38330,40989,956,False,True,-1,14111.722299
2025-04-04,5074.080078,38330,43593,956,False,True,-1,13268.552461
2025-04-07,5062.250000,43690,43690,1000,False,False,0,13237.617196

In [9]:
stats = bt.stats()
stats

Start                     2023-01-03 00:00:00
End                       2025-04-07 00:00:00
Duration                    825 days 00:00:00
Exposure Time [%]                   96.296296
Equity Start                            10000
Equity Peak                             43690
Equity Final                            43690
Equity Return [%]                       336.9
Balance Start                           10000
Balance Peak                            43690
Balance Final                           43690
Balance Return [%]                      336.9
Gross Return [%]                       159.71
Total Commissions                        1000
Return (Ann.) [%]                   92.804468
Volatility (Ann.) [%]               25.731644
CAGR [%]                            92.094352
Sharpe Ratio                         3.412315
Sortino Ratio                       14.088748
Calmar Ratio                        27.526715
Max. Drawdown [%]                   -3.371433
Avg. Drawdown [%]                    -0.91953
Max. Drawdown Duration       34 days 00:00:00
Avg. Drawdown Duration        7 days 00:00:00
Total Trades                               19
Win Rate [%]                        94.736842
Best Trade [%]                      27.614228
Worst Trade [%]                      -2.44859
Avg. Trade [%]                       8.185924
Max. Trade Duration         153 days 00:00:00
Avg. Trade Duration          42 days 00:00:00
Profit Factor                       66.224009
Expectancy [%]                       8.405625
SQN                                  5.218612
Kelly Criterion                      0.925864
Candles                                   567
Long Trades                                 9
Short Trades                               10
Exposure Trades [%]                      0.03
dtype: object

In [ ]:
bt.plot(w=700, h=500, show_signals=False)